package SequencialDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Actor = 0;
  public static final int Alt = 1;
  public static final int AltAndElse = 2;
  public static final int AsyncFunction = 3;
  public static final int Entity = 4;
  public static final int Event = 5;
  public static final int Function = 6;
  public static final int Loop = 7;
  public static final int Model = 8;
  public static final int NewObjectFunction = 9;
  public static final int Object = 10;
  public static final int ObjectInstance = 11;
  public static final int Structure = 12;
  public static final int SyncFunction = 13;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL);
    builder.put(0x4ad1f17994f7d0b1L, Actor);
    builder.put(0x4ad1f17994f63fc1L, Alt);
    builder.put(0x4ad1f17994f63fc0L, AltAndElse);
    builder.put(0x4ad1f17994f63e37L, AsyncFunction);
    builder.put(0x4ad1f17994f63fc3L, Entity);
    builder.put(0x4ad1f17994f63d7eL, Event);
    builder.put(0x4ad1f17994f63d81L, Function);
    builder.put(0x4ad1f17994f63fbfL, Loop);
    builder.put(0x4ad1f17994f53793L, Model);
    builder.put(0x311ac1fe639f0326L, NewObjectFunction);
    builder.put(0x4ad1f17994f63e3bL, Object);
    builder.put(0x311ac1fe6399eb50L, ObjectInstance);
    builder.put(0x4ad1f17994f63fbbL, Structure);
    builder.put(0x4ad1f17994f63d93L, SyncFunction);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
