package SequencialDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActor = createDescriptorForActor();
  /*package*/ final ConceptDescriptor myConceptAlt = createDescriptorForAlt();
  /*package*/ final ConceptDescriptor myConceptAltAndElse = createDescriptorForAltAndElse();
  /*package*/ final ConceptDescriptor myConceptAsyncFunction = createDescriptorForAsyncFunction();
  /*package*/ final ConceptDescriptor myConceptEntity = createDescriptorForEntity();
  /*package*/ final ConceptDescriptor myConceptEvent = createDescriptorForEvent();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptLoop = createDescriptorForLoop();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptNewObjectFunction = createDescriptorForNewObjectFunction();
  /*package*/ final ConceptDescriptor myConceptObject = createDescriptorForObject();
  /*package*/ final ConceptDescriptor myConceptObjectInstance = createDescriptorForObjectInstance();
  /*package*/ final ConceptDescriptor myConceptStructure = createDescriptorForStructure();
  /*package*/ final ConceptDescriptor myConceptSyncFunction = createDescriptorForSyncFunction();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActor, myConceptAlt, myConceptAltAndElse, myConceptAsyncFunction, myConceptEntity, myConceptEvent, myConceptFunction, myConceptLoop, myConceptModel, myConceptNewObjectFunction, myConceptObject, myConceptObjectInstance, myConceptStructure, myConceptSyncFunction);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actor:
        return myConceptActor;
      case LanguageConceptSwitch.Alt:
        return myConceptAlt;
      case LanguageConceptSwitch.AltAndElse:
        return myConceptAltAndElse;
      case LanguageConceptSwitch.AsyncFunction:
        return myConceptAsyncFunction;
      case LanguageConceptSwitch.Entity:
        return myConceptEntity;
      case LanguageConceptSwitch.Event:
        return myConceptEvent;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.Loop:
        return myConceptLoop;
      case LanguageConceptSwitch.Model:
        return myConceptModel;
      case LanguageConceptSwitch.NewObjectFunction:
        return myConceptNewObjectFunction;
      case LanguageConceptSwitch.Object:
        return myConceptObject;
      case LanguageConceptSwitch.ObjectInstance:
        return myConceptObjectInstance;
      case LanguageConceptSwitch.Structure:
        return myConceptStructure;
      case LanguageConceptSwitch.SyncFunction:
        return myConceptSyncFunction;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Actor", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f7d0b1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431799985");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAlt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Alt", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc1L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697345");
    b.version(3);
    b.property("condition", 0x4ad1f17994f7cf2aL).type(PrimitiveTypeId.STRING).origin("5391355733431799594").done();
    b.aggregate("thenFunctions", 0x311ac1fe63968e5fL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("3538353755589611103").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAltAndElse() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "AltAndElse", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc0L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697344");
    b.version(3);
    b.property("condition", 0x4ad1f17994f7cf2fL).type(PrimitiveTypeId.STRING).origin("5391355733431799599").done();
    b.aggregate("thenFunctions", 0x311ac1fe63968d7eL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("3538353755589610878").done();
    b.aggregate("elseFunctions", 0x311ac1fe63968efaL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("3538353755589611258").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAsyncFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "AsyncFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e37L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696951");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Entity", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.class_(false, true, false);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697347");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Event", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d7eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696766");
    b.version(3);
    b.aggregate("entities", 0x4ad1f17994f63fceL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(false).origin("5391355733431697358").done();
    b.aggregate("actor", 0x4ad1f17994f7d0ccL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f7d0b1L).optional(false).ordered(true).multiple(false).origin("5391355733431800012").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Function", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.class_(false, true, false);
    // extends: SequencialDiagramDSL.structure.Entity
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696769");
    b.version(3);
    b.property("parameters", 0x4ad1f17994f63d86L).type(PrimitiveTypeId.STRING).origin("5391355733431696774").done();
    b.property("retrurnValue", 0x4ad1f17994f63d88L).type(PrimitiveTypeId.STRING).origin("5391355733431696776").done();
    b.aggregate("functions", 0x4ad1f17994f63e32L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L).optional(true).ordered(true).multiple(true).origin("5391355733431696946").done();
    b.aggregate("calling", 0x4ad1f17994f63e38L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x311ac1fe6399eb50L).optional(false).ordered(true).multiple(false).origin("5391355733431696952").done();
    b.aggregate("calledFrom", 0x4ad1f17994f63ed9L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x311ac1fe6399eb50L).optional(false).ordered(true).multiple(false).origin("5391355733431697113").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLoop() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Loop", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbfL);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697343");
    b.version(3);
    b.property("condition", 0x311ac1fe6395ce7eL).type(PrimitiveTypeId.STRING).origin("3538353755589561982").done();
    b.aggregate("functions", 0x311ac1fe63968c95L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(true).ordered(true).multiple(true).origin("3538353755589610645").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Model", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f53793L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431629715");
    b.version(3);
    b.aggregate("event", 0x4ad1f17994f756e8L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d7eL).optional(false).ordered(true).multiple(false).origin("5391355733431768808").done();
    b.aggregate("predefinedObjects", 0x311ac1fe6399113eL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL).optional(true).ordered(true).multiple(true).origin("3538353755589775678").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNewObjectFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "NewObjectFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x311ac1fe639f0326L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3538353755590165286");
    b.version(3);
    b.aggregate("createdObject", 0x311ac1fe639f032eL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL).optional(false).ordered(true).multiple(false).origin("3538353755590165294").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Object", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696955");
    b.version(3);
    b.property("class", 0x4ad1f17994f63e3eL).type(PrimitiveTypeId.STRING).origin("5391355733431696958").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ObjectInstance", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x311ac1fe6399eb50L);
    b.class_(false, false, false);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3538353755589831504");
    b.version(3);
    b.associate("object", 0x311ac1fe6399eb51L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL).optional(true).origin("3538353755589831505").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Structure", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.class_(false, true, false);
    // extends: SequencialDiagramDSL.structure.Entity
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697339");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSyncFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "SyncFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d93L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696787");
    b.version(3);
    return b.create();
  }
}
