package SequencialDiagramDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActor = createDescriptorForActor();
  /*package*/ final ConceptDescriptor myConceptAlt = createDescriptorForAlt();
  /*package*/ final ConceptDescriptor myConceptAsyncFunction = createDescriptorForAsyncFunction();
  /*package*/ final ConceptDescriptor myConceptClass = createDescriptorForClass();
  /*package*/ final ConceptDescriptor myConceptEvent = createDescriptorForEvent();
  /*package*/ final ConceptDescriptor myConceptExpression = createDescriptorForExpression();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptFunctionParameter = createDescriptorForFunctionParameter();
  /*package*/ final ConceptDescriptor myConceptLoop = createDescriptorForLoop();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptNewObjectFunction = createDescriptorForNewObjectFunction();
  /*package*/ final ConceptDescriptor myConceptObject = createDescriptorForObject();
  /*package*/ final ConceptDescriptor myConceptObjectExpression = createDescriptorForObjectExpression();
  /*package*/ final ConceptDescriptor myConceptObjectExpressionInstance = createDescriptorForObjectExpressionInstance();
  /*package*/ final ConceptDescriptor myConceptObjectExpressionReference = createDescriptorForObjectExpressionReference();
  /*package*/ final ConceptDescriptor myConceptOpt = createDescriptorForOpt();
  /*package*/ final ConceptDescriptor myConceptRef = createDescriptorForRef();
  /*package*/ final ConceptDescriptor myConceptReturnValue = createDescriptorForReturnValue();
  /*package*/ final ConceptDescriptor myConceptReturnValueInstance = createDescriptorForReturnValueInstance();
  /*package*/ final ConceptDescriptor myConceptReturnValueReference = createDescriptorForReturnValueReference();
  /*package*/ final ConceptDescriptor myConceptStructure = createDescriptorForStructure();
  /*package*/ final ConceptDescriptor myConceptSyncFunction = createDescriptorForSyncFunction();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActor, myConceptAlt, myConceptAsyncFunction, myConceptClass, myConceptEvent, myConceptExpression, myConceptFunction, myConceptFunctionParameter, myConceptLoop, myConceptModel, myConceptNewObjectFunction, myConceptObject, myConceptObjectExpression, myConceptObjectExpressionInstance, myConceptObjectExpressionReference, myConceptOpt, myConceptRef, myConceptReturnValue, myConceptReturnValueInstance, myConceptReturnValueReference, myConceptStructure, myConceptSyncFunction, myConceptType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actor:
        return myConceptActor;
      case LanguageConceptSwitch.Alt:
        return myConceptAlt;
      case LanguageConceptSwitch.AsyncFunction:
        return myConceptAsyncFunction;
      case LanguageConceptSwitch.Class:
        return myConceptClass;
      case LanguageConceptSwitch.Event:
        return myConceptEvent;
      case LanguageConceptSwitch.Expression:
        return myConceptExpression;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.FunctionParameter:
        return myConceptFunctionParameter;
      case LanguageConceptSwitch.Loop:
        return myConceptLoop;
      case LanguageConceptSwitch.Model:
        return myConceptModel;
      case LanguageConceptSwitch.NewObjectFunction:
        return myConceptNewObjectFunction;
      case LanguageConceptSwitch.Object:
        return myConceptObject;
      case LanguageConceptSwitch.ObjectExpression:
        return myConceptObjectExpression;
      case LanguageConceptSwitch.ObjectExpressionInstance:
        return myConceptObjectExpressionInstance;
      case LanguageConceptSwitch.ObjectExpressionReference:
        return myConceptObjectExpressionReference;
      case LanguageConceptSwitch.Opt:
        return myConceptOpt;
      case LanguageConceptSwitch.Ref:
        return myConceptRef;
      case LanguageConceptSwitch.ReturnValue:
        return myConceptReturnValue;
      case LanguageConceptSwitch.ReturnValueInstance:
        return myConceptReturnValueInstance;
      case LanguageConceptSwitch.ReturnValueReference:
        return myConceptReturnValueReference;
      case LanguageConceptSwitch.Structure:
        return myConceptStructure;
      case LanguageConceptSwitch.SyncFunction:
        return myConceptSyncFunction;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Actor", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f7d0b1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431799985");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAlt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Alt", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc0L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697344");
    b.version(3);
    b.property("condition", 0x4ad1f17994f7cf2fL).type(PrimitiveTypeId.STRING).origin("5391355733431799599").done();
    b.aggregate("thenFunctions", 0x311ac1fe63968d7eL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("3538353755589610878").done();
    b.aggregate("elseFunctions", 0x311ac1fe63968efaL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("3538353755589611258").done();
    b.alias("Alt");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAsyncFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "AsyncFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e37L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696951");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Class", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x6c34d263b52968d4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/7797088180568156372");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEvent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Event", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d7eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696766");
    b.version(3);
    b.aggregate("function", 0x4ad1f17994f63fceL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(false).origin("5391355733431697358").done();
    b.aggregate("actor", 0x4ad1f17994f7d0ccL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f7d0b1L).optional(false).ordered(true).multiple(false).origin("5391355733431800012").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Expression", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.class_(false, true, false);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697347");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Function", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.class_(false, true, false);
    // extends: SequencialDiagramDSL.structure.Expression
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696769");
    b.version(3);
    b.aggregate("functions", 0x4ad1f17994f63e32L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L).optional(true).ordered(true).multiple(true).origin("5391355733431696946").done();
    b.aggregate("calling", 0x4ad1f17994f63e38L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0847L).optional(false).ordered(true).multiple(false).origin("5391355733431696952").done();
    b.aggregate("calledFrom", 0x4ad1f17994f63ed9L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0847L).optional(false).ordered(true).multiple(false).origin("5391355733431697113").done();
    b.aggregate("parameters", 0x6c34d263b51331cfL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f8257dad8L).optional(true).ordered(true).multiple(true).origin("7797088180566700495").done();
    b.aggregate("returnType", 0x6c34d263b51e4928L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x6c34d263b52968d4L).optional(false).ordered(true).multiple(false).origin("7797088180567427368").done();
    b.aggregate("returnValue", 0x20d68e7f82661eeaL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee6L).optional(false).ordered(true).multiple(false).origin("2366235332529495786").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunctionParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "FunctionParameter", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f8257dad8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/2366235332528560856");
    b.version(3);
    b.aggregate("class", 0x20d68e7f8260fac7L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x6c34d263b52968d4L).optional(false).ordered(true).multiple(false).origin("2366235332529158855").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLoop() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Loop", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbfL);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697343");
    b.version(3);
    b.property("condition", 0x311ac1fe6395ce7eL).type(PrimitiveTypeId.STRING).origin("3538353755589561982").done();
    b.aggregate("functions", 0x311ac1fe63968c95L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(true).ordered(true).multiple(true).origin("3538353755589610645").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Model", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f53793L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431629715");
    b.version(3);
    b.aggregate("events", 0x4ad1f17994f756e8L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d7eL).optional(false).ordered(true).multiple(true).origin("5391355733431768808").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNewObjectFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "NewObjectFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x311ac1fe639f0326L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3538353755590165286");
    b.version(3);
    b.aggregate("createdObject", 0x311ac1fe639f032eL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL).optional(false).ordered(true).multiple(false).origin("3538353755590165294").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Object", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696955");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ObjectExpression", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0847L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3965880733921970247");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectExpressionInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ObjectExpressionInstance", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0819L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.ObjectExpression
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0847L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3965880733921970201");
    b.version(3);
    b.aggregate("object", 0x3709a383ef10fad4L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63e3bL).optional(false).ordered(true).multiple(false).origin("3965880733923343060").done();
    b.aggregate("class", 0x3709a383ef10fad5L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x6c34d263b52968d4L).optional(false).ordered(true).multiple(false).origin("3965880733923343061").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectExpressionReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ObjectExpressionReference", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc081aL);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.ObjectExpression
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0847L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/3965880733921970202");
    b.version(3);
    b.associate("objectExcpressionRef", 0x3709a383eefc081bL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x3709a383eefc0819L).optional(false).origin("3965880733921970203").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOpt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Opt", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x64e214356fd6e8e9L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Structure
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/7269394968271579369");
    b.version(3);
    b.property("condition", 0x64e214356fd6ec8fL).type(PrimitiveTypeId.STRING).origin("7269394968271580303").done();
    b.aggregate("functions", 0x64e214356fd6ecf8L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L).optional(false).ordered(true).multiple(true).origin("7269394968271580408").done();
    b.alias("Opt");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Ref", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x64e214356fdd2dcdL);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Expression
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/7269394968271990221");
    b.version(3);
    b.associate("model", 0x64e214356fdd2dfaL).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f53793L).optional(false).origin("7269394968271990266").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturnValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ReturnValue", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee6L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/2366235332529495782");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturnValueInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ReturnValueInstance", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee1L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.ReturnValue
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/2366235332529495777");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturnValueReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "ReturnValueReference", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee2L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.ReturnValue
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee6L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/2366235332529495778");
    b.version(3);
    b.associate("returnValueInstance", 0x20d68e7f82661ee3L).target(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x20d68e7f82661ee1L).optional(false).origin("2366235332529495779").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Structure", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fbbL);
    b.class_(false, true, false);
    // extends: SequencialDiagramDSL.structure.Expression
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63fc3L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431697339");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSyncFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "SyncFunction", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d93L);
    b.class_(false, false, false);
    // extends: SequencialDiagramDSL.structure.Function
    b.super_(0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x4ad1f17994f63d81L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/5391355733431696787");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("SequencialDiagramDSL", "Type", 0xa40b2b6aa7624d4dL, 0xa6710bcaedd9d57eL, 0x6c34d263b51f34c3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f6514430-000f-4d0a-9d53-7bfec5a1a776(SequencialDiagramDSL.structure)/7797088180567487683");
    b.version(3);
    return b.create();
  }
}
